- name: configure rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: installed

  - name: enable and start server
    ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

  - name: create rabbitmq user and giving permissions
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          red_priv: .*
          write_priv: .*
      state: present
