- name: configure user component
  hosts: user
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs  
    ansible.builtin.dnf: 
      name: nodejs
      state: present
    
  - name: add roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: extract user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    community.general.npm: # this is npm install
      path: /app

  - name: copy user service to system directory
    ansible.builtin.copy:
      src: user.service
      path: /etc/systemd/system/user.service
  
  - name: system daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
